# Docker Testing Environment Inventory
# For testing deployments before production
---
wordpress_servers:
  hosts:
    docker-test:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: ansible
      ansible_ssh_pass: ansible123
      ansible_become_pass: ansible123
      domain_name: localhost

      # SSL Configuration (usually disabled for testing)
      ssl_enabled: false

      # WordPress Database (Test credentials)
      mysql_root_password: "test_root_password"
      wordpress_db_name: "wordpress"
      wordpress_db_user: "wp_user"
      wordpress_db_password: "test_wp_password"

      # WordPress Admin (Test credentials)
      wp_admin_user: "admin"
      wp_admin_password: "test_admin_password"
      wp_admin_email: "admin@localhost"
      wp_site_title: "Test WordPress Site"

      # Ultimate Features (for testing Ultimate-Playbook)
      enable_redis: true
      enable_opcache: true
