# Production Server Configuration
# SECURITY: Change all passwords before deployment!
---
wordpress_servers:
  hosts:
    your-server.example.com:
      ansible_host: YOUR_SERVER_IP
      ansible_user: your_user
      # ansible_ssh_pass: "your_password"  # Use SSH keys instead!
      # ansible_become_pass: "your_sudo_password"  # Use passwordless sudo instead!
      domain_name: example.com

      # SSL Configuration
      ssl_enabled: false  # Set to true for HTTPS with Let's Encrypt
      ssl_email: admin@example.com  # Required if ssl_enabled=true

      # WordPress Database (CHANGE THESE!)
      mysql_root_password: "CHANGE_ME_ROOT_PASSWORD"
      wordpress_db_name: "wordpress"
      wordpress_db_user: "wp_user"
      wordpress_db_password: "CHANGE_ME_WP_PASSWORD"

      # WordPress Admin (CHANGE THESE!)
      wp_admin_user: "admin"
      wp_admin_password: "CHANGE_ME_ADMIN_PASSWORD"
      wp_admin_email: "admin@example.com"
      wp_site_title: "My WordPress Site"

      # Ultimate Performance Features (for lemp-wordpress-ultimate.yml)
      enable_redis: false           # Redis object caching
      enable_opcache: false         # PHP OPcache optimization
      enable_nginx_optimization: false  # Advanced Nginx performance tuning
