name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-check
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you deploying to?
      options:
        - Docker (testing)
        - Ubuntu Server
        - Debian Server  
        - CentOS/RHEL/Rocky Linux
        - Cloud Instance (AWS/GCP/Azure)
        - VPS
        - Bare Metal
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "Example: Ubuntu 24.04 LTS, CentOS Stream 9"
      placeholder: "Ubuntu 24.04 LTS"
    validations:
      required: true

  - type: input
    id: ansible-version
    attributes:
      label: Ansible Version
      description: Output of `ansible --version`
      placeholder: "ansible [core 2.15.0]"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
        3. Check log '...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (ansible-playbook -vv output, error logs, etc.)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your inventory file and any custom variables (please remove sensitive information)
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
